export const UI_TERMS = {
  launcher: {
    appName: "Stell▲rNest",
    tagline: "Éditeur visuel local-first",
    newProject: "Nouveau projet",
    recentProject: "Projet récent",
    designerLabel: "Concepteur",
    designerName: "Phey Rainville (PH3YNYX.Studio)",
    websiteUrl: "https://ph3ynyx.dev/",
    websiteLabel: "ph3ynyx.dev",
    changelogTitle: "Notes de mise à jour",
    changelogBody: "v0.1 — premières fondations : thème, layout, zoom",
    themeSectionTitle: "Thème de départ",
    themeSectionBadge: "Bientôt disponible",
    newProjectDialogTitle: "Nouveau projet",
    projectNameLabel: "Nom du projet",
    canvasModeLabel: "Mode",
    canvasModeMobile: "Mobile",
    canvasModeDesktop: "Desktop",
    createProject: "Créer",
    cancel: "Annuler",
  },
  header: {
    projectName: "Projet sans nom",
    status: "Brouillon",
    exportButton: "Exporter",
    exportSuccess: "Exporté ✓",
    exportError: "Échec de l'export",
    zoomReset: "Ajuster",
    previewButton: "Aperçu",
    backToEdit: "Retour à l'édition",
    previewUnavailable: "Exporte d'abord pour voir l'aperçu",
  },
  panels: {
    library: "Librairie",
    style: "Style",
    layers: "Calques",
  },
  library: {
    cardLabel: "Carte",
  },
  stylePanel: {
    canvasBackgroundLabel: "Couleur de fond du canvas",
    deleteElement: "Supprimer",
  },
};
